### ISSUE TITLE
Documentation unreachable due to Mojohaus shutdown

### ISSUE THREAD

**Issue by debovema** [in-mind-cloud/truezip-maven#1]
The Maven plugin documentation (http://mojo.codehaus.org/truezip/truezip-maven-plugin) is unavailable because the Mojohaus project shut down in June 2015.

Is there a place where the site is available? Or is it planned to upload the site somewhere?

**Comment by tobias-hammerschmidt** [comment]
Please note that this is an inofficial fork of the truezip-maven plugin. The official project can be found at https://github.com/mojohaus/truezip. Not sure whats the state of the documentation though.
